# Site settings
title: The Kyn Project
description: > # this means to ignore newlines until "baseurl:"
  Experiments leveraging technology for the greater good

# Build settings
exclude:
- README.md

markdown: kramdown

kramdown:
  input: GFM
